//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO_Voyage_UIL.ServiceReferenceBanqueFournisseur {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ASP_06_BANQUE_WCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dtoCb", Namespace="http://schemas.datacontract.org/2004/07/ASP_06_BANQUE_WCF")]
    [System.SerializableAttribute()]
    public partial class dtoCb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CBDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CryptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CBDate {
            get {
                return this.CBDateField;
            }
            set {
                if ((this.CBDateField.Equals(value) != true)) {
                    this.CBDateField = value;
                    this.RaisePropertyChanged("CBDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Client {
            get {
                return this.ClientField;
            }
            set {
                if ((this.ClientField.Equals(value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crypto {
            get {
                return this.CryptoField;
            }
            set {
                if ((object.ReferenceEquals(this.CryptoField, value) != true)) {
                    this.CryptoField = value;
                    this.RaisePropertyChanged("Crypto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num {
            get {
                return this.NumField;
            }
            set {
                if ((object.ReferenceEquals(this.NumField, value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBanqueFournisseur.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType GetDataUsingDataContract(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType> GetDataUsingDataContractAsync(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckCb", ReplyAction="http://tempuri.org/IService1/CheckCbResponse")]
        bool CheckCb(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckCb", ReplyAction="http://tempuri.org/IService1/CheckCbResponse")]
        System.Threading.Tasks.Task<bool> CheckCbAsync(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DebiterCarte", ReplyAction="http://tempuri.org/IService1/DebiterCarteResponse")]
        bool DebiterCarte(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb, double prix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DebiterCarte", ReplyAction="http://tempuri.org/IService1/DebiterCarteResponse")]
        System.Threading.Tasks.Task<bool> DebiterCarteAsync(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb, double prix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckDispo", ReplyAction="http://tempuri.org/IService1/CheckDispoResponse")]
        bool CheckDispo(int codeVoyage, int nbPlaces);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckDispo", ReplyAction="http://tempuri.org/IService1/CheckDispoResponse")]
        System.Threading.Tasks.Task<bool> CheckDispoAsync(int codeVoyage, int nbPlaces);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.IService1>, BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType GetDataUsingDataContract(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType> GetDataUsingDataContractAsync(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool CheckCb(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb) {
            return base.Channel.CheckCb(cb);
        }
        
        public System.Threading.Tasks.Task<bool> CheckCbAsync(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb) {
            return base.Channel.CheckCbAsync(cb);
        }
        
        public bool DebiterCarte(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb, double prix) {
            return base.Channel.DebiterCarte(cb, prix);
        }
        
        public System.Threading.Tasks.Task<bool> DebiterCarteAsync(BO_Voyage_UIL.ServiceReferenceBanqueFournisseur.dtoCb cb, double prix) {
            return base.Channel.DebiterCarteAsync(cb, prix);
        }
        
        public bool CheckDispo(int codeVoyage, int nbPlaces) {
            return base.Channel.CheckDispo(codeVoyage, nbPlaces);
        }
        
        public System.Threading.Tasks.Task<bool> CheckDispoAsync(int codeVoyage, int nbPlaces) {
            return base.Channel.CheckDispoAsync(codeVoyage, nbPlaces);
        }
    }
}
