//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO_Voyage_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampagneClient
    {
        public long Id { get; set; }
        public long IdCamp { get; set; }
        public long IdClient { get; set; }
    
        public virtual Campagne Campagne { get; set; }
        public virtual Client Client { get; set; }
    }
}
