//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO_Voyage_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campagne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campagne()
        {
            this.CampagneClients = new HashSet<CampagneClient>();
        }
    
        public long Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateDeCreation { get; set; }
        public Nullable<System.DateTime> DateDeLimite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampagneClient> CampagneClients { get; set; }
    }
}
