//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO_Voyage_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BOVoyageContext : DbContext
    {
        public BOVoyageContext()
            : base("name=BOVoyageContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campagne> Campagnes { get; set; }
        public virtual DbSet<CampagneClient> CampagneClients { get; set; }
        public virtual DbSet<CarteBancaire> CarteBancaires { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Dossier> Dossiers { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Voyage> Voyages { get; set; }
        public virtual DbSet<Voyageur> Voyageurs { get; set; }
    
        [DbFunction("BOVoyageContext", "GetClient")]
        public virtual IQueryable<GetClient_Result> GetClient(string identifiant, string password)
        {
            var identifiantParameter = identifiant != null ?
                new ObjectParameter("Identifiant", identifiant) :
                new ObjectParameter("Identifiant", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetClient_Result>("[BOVoyageContext].[GetClient](@Identifiant, @Password)", identifiantParameter, passwordParameter);
        }
    
        [DbFunction("BOVoyageContext", "GetClient_Email")]
        public virtual IQueryable<GetClient_Email_Result> GetClient_Email(string identifiant, string password)
        {
            var identifiantParameter = identifiant != null ?
                new ObjectParameter("Identifiant", identifiant) :
                new ObjectParameter("Identifiant", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetClient_Email_Result>("[BOVoyageContext].[GetClient_Email](@Identifiant, @Password)", identifiantParameter, passwordParameter);
        }
    
        [DbFunction("BOVoyageContext", "GetDossier")]
        public virtual IQueryable<GetDossier_Result> GetDossier(string identifiant, string password)
        {
            var identifiantParameter = identifiant != null ?
                new ObjectParameter("Identifiant", identifiant) :
                new ObjectParameter("Identifiant", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDossier_Result>("[BOVoyageContext].[GetDossier](@Identifiant, @Password)", identifiantParameter, passwordParameter);
        }
    
        [DbFunction("BOVoyageContext", "GetPrice")]
        public virtual IQueryable<GetPrice_Result> GetPrice(string identifiant, string password, Nullable<int> age, Nullable<decimal> taux)
        {
            var identifiantParameter = identifiant != null ?
                new ObjectParameter("Identifiant", identifiant) :
                new ObjectParameter("Identifiant", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var tauxParameter = taux.HasValue ?
                new ObjectParameter("Taux", taux) :
                new ObjectParameter("Taux", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPrice_Result>("[BOVoyageContext].[GetPrice](@Identifiant, @Password, @Age, @Taux)", identifiantParameter, passwordParameter, ageParameter, tauxParameter);
        }
    
        [DbFunction("BOVoyageContext", "GetVoyageur_Price")]
        public virtual IQueryable<GetVoyageur_Price_Result> GetVoyageur_Price(Nullable<int> idVoyageur, Nullable<int> age, Nullable<decimal> taux)
        {
            var idVoyageurParameter = idVoyageur.HasValue ?
                new ObjectParameter("IdVoyageur", idVoyageur) :
                new ObjectParameter("IdVoyageur", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var tauxParameter = taux.HasValue ?
                new ObjectParameter("Taux", taux) :
                new ObjectParameter("Taux", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetVoyageur_Price_Result>("[BOVoyageContext].[GetVoyageur_Price](@IdVoyageur, @Age, @Taux)", idVoyageurParameter, ageParameter, tauxParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> EnregistreDossier(Nullable<long> idVoyage, string emailClient, string numCBClient, Nullable<int> nbVoyageur, Nullable<long> idClient, Nullable<long> idCB)
        {
            var idVoyageParameter = idVoyage.HasValue ?
                new ObjectParameter("IdVoyage", idVoyage) :
                new ObjectParameter("IdVoyage", typeof(long));
    
            var emailClientParameter = emailClient != null ?
                new ObjectParameter("EmailClient", emailClient) :
                new ObjectParameter("EmailClient", typeof(string));
    
            var numCBClientParameter = numCBClient != null ?
                new ObjectParameter("NumCBClient", numCBClient) :
                new ObjectParameter("NumCBClient", typeof(string));
    
            var nbVoyageurParameter = nbVoyageur.HasValue ?
                new ObjectParameter("NbVoyageur", nbVoyageur) :
                new ObjectParameter("NbVoyageur", typeof(int));
    
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(long));
    
            var idCBParameter = idCB.HasValue ?
                new ObjectParameter("IdCB", idCB) :
                new ObjectParameter("IdCB", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("EnregistreDossier", idVoyageParameter, emailClientParameter, numCBClientParameter, nbVoyageurParameter, idClientParameter, idCBParameter);
        }
    
        public virtual ObjectResult<Filtre_Result> Filtre(string typeVoy, Nullable<long> idC, Nullable<long> idP, Nullable<long> idR, Nullable<int> ageMin, Nullable<int> ageMax)
        {
            var typeVoyParameter = typeVoy != null ?
                new ObjectParameter("TypeVoy", typeVoy) :
                new ObjectParameter("TypeVoy", typeof(string));
    
            var idCParameter = idC.HasValue ?
                new ObjectParameter("idC", idC) :
                new ObjectParameter("idC", typeof(long));
    
            var idPParameter = idP.HasValue ?
                new ObjectParameter("idP", idP) :
                new ObjectParameter("idP", typeof(long));
    
            var idRParameter = idR.HasValue ?
                new ObjectParameter("idR", idR) :
                new ObjectParameter("idR", typeof(long));
    
            var ageMinParameter = ageMin.HasValue ?
                new ObjectParameter("AgeMin", ageMin) :
                new ObjectParameter("AgeMin", typeof(int));
    
            var ageMaxParameter = ageMax.HasValue ?
                new ObjectParameter("AgeMax", ageMax) :
                new ObjectParameter("AgeMax", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Filtre_Result>("Filtre", typeVoyParameter, idCParameter, idPParameter, idRParameter, ageMinParameter, ageMaxParameter);
        }
    
        public virtual ObjectResult<GetListeContinent_Result> GetListeContinent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListeContinent_Result>("GetListeContinent");
        }
    
        public virtual ObjectResult<GetListePays_Result> GetListePays(Nullable<int> choixC)
        {
            var choixCParameter = choixC.HasValue ?
                new ObjectParameter("choixC", choixC) :
                new ObjectParameter("choixC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListePays_Result>("GetListePays", choixCParameter);
        }
    
        public virtual ObjectResult<GetListeRegion_Result> GetListeRegion(Nullable<int> choixP, Nullable<int> choixC)
        {
            var choixPParameter = choixP.HasValue ?
                new ObjectParameter("choixP", choixP) :
                new ObjectParameter("choixP", typeof(int));
    
            var choixCParameter = choixC.HasValue ?
                new ObjectParameter("choixC", choixC) :
                new ObjectParameter("choixC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListeRegion_Result>("GetListeRegion", choixPParameter, choixCParameter);
        }
    
        public virtual ObjectResult<GetListeVoyage_Result> GetListeVoyage(Nullable<int> choixC, Nullable<int> choixP, Nullable<int> choixR)
        {
            var choixCParameter = choixC.HasValue ?
                new ObjectParameter("choixC", choixC) :
                new ObjectParameter("choixC", typeof(int));
    
            var choixPParameter = choixP.HasValue ?
                new ObjectParameter("choixP", choixP) :
                new ObjectParameter("choixP", typeof(int));
    
            var choixRParameter = choixR.HasValue ?
                new ObjectParameter("choixR", choixR) :
                new ObjectParameter("choixR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListeVoyage_Result>("GetListeVoyage", choixCParameter, choixPParameter, choixRParameter);
        }
    
        public virtual ObjectResult<string> GetMotdepasse(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetMotdepasse", idParameter);
        }
    
        public virtual ObjectResult<string> Sp_GenereId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_GenereId");
        }
    
        public virtual ObjectResult<string> Sp_Get_Voyage_Type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_Get_Voyage_Type");
        }
    
        public virtual ObjectResult<Sp_GetCb_Result> Sp_GetCb(Nullable<long> idCb)
        {
            var idCbParameter = idCb.HasValue ?
                new ObjectParameter("IdCb", idCb) :
                new ObjectParameter("IdCb", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetCb_Result>("Sp_GetCb", idCbParameter);
        }
    
        public virtual ObjectResult<Sp_GetDossier_Result> Sp_GetDossier(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetDossier_Result>("Sp_GetDossier", idParameter);
        }
    
        public virtual ObjectResult<Sp_GetDossier_ClientInfo_Result> Sp_GetDossier_ClientInfo(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetDossier_ClientInfo_Result>("Sp_GetDossier_ClientInfo", idParameter);
        }
    
        public virtual ObjectResult<Sp_GetPrice_Result> Sp_GetPrice(string identifiant, string password, Nullable<int> age, Nullable<decimal> taux)
        {
            var identifiantParameter = identifiant != null ?
                new ObjectParameter("Identifiant", identifiant) :
                new ObjectParameter("Identifiant", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var tauxParameter = taux.HasValue ?
                new ObjectParameter("Taux", taux) :
                new ObjectParameter("Taux", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetPrice_Result>("Sp_GetPrice", identifiantParameter, passwordParameter, ageParameter, tauxParameter);
        }
    
        public virtual ObjectResult<Sp_GetVoyage_Result> Sp_GetVoyage(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetVoyage_Result>("Sp_GetVoyage", idParameter);
        }
    
        public virtual ObjectResult<Sp_GetVoyageClient_Result> Sp_GetVoyageClient(Nullable<long> idClient)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetVoyageClient_Result>("Sp_GetVoyageClient", idClientParameter);
        }
    
        public virtual ObjectResult<Sp_GetVoyageur_Price_Result> Sp_GetVoyageur_Price(Nullable<int> idVoyageur, Nullable<int> age, Nullable<decimal> taux)
        {
            var idVoyageurParameter = idVoyageur.HasValue ?
                new ObjectParameter("IdVoyageur", idVoyageur) :
                new ObjectParameter("IdVoyageur", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var tauxParameter = taux.HasValue ?
                new ObjectParameter("Taux", taux) :
                new ObjectParameter("Taux", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetVoyageur_Price_Result>("Sp_GetVoyageur_Price", idVoyageurParameter, ageParameter, tauxParameter);
        }
    
        public virtual int Sp_SetClient_Price(Nullable<long> id, Nullable<decimal> price)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_SetClient_Price", idParameter, priceParameter);
        }
    }
}
