//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO_Voyage_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyage()
        {
            this.Dossiers = new HashSet<Dossier>();
        }
    
        public long Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateDepart { get; set; }
        public Nullable<System.DateTime> DateRetour { get; set; }
        public Nullable<long> Dispo { get; set; }
        public Nullable<double> Prix { get; set; }
        public long IdRegion { get; set; }
        public string Url { get; set; }
        public string TypeVoyage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dossier> Dossiers { get; set; }
        public virtual Region Region { get; set; }
    }
}
